"""initial schema

Revision ID: a43a577cf911
Revises: 
Create Date: 2026-10-02 13:36:23.463264
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a43a577cf911'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=8), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('drift_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=8), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runs_affected', sa.Integer(), nullable=False),
    sa.Column('opened_by_eval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_drift_incidents_status'), 'drift_incidents', ['status'], unique=False, schema='app')
    op.create_table('drift_scenarios',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    schema='app'
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('drift_scenario', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('declined', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('workflow', sa.String(length=40), nullable=True),
    sa.Column('workflow_source', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_runs_decision'), 'runs', ['decision'], unique=False, schema='app')
    op.create_table('supplier_on_time',
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pos_received', sa.Integer(), nullable=False),
    sa.Column('pos_on_time', sa.Integer(), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('open_late_pos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='dw'
    )
    op.create_table('wo_cycle_time',
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('closed_wos', sa.Integer(), nullable=False),
    sa.Column('avg_cycle_days', sa.Float(), nullable=False),
    sa.Column('last_cycle_days', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('part_number'),
    schema='dw'
    )
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=16), nullable=False),
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('unit_cost_usd', sa.Float(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('po_id'),
    schema='erp'
    )
    op.create_index(op.f('ix_erp_purchase_orders_part_number'), 'purchase_orders', ['part_number'], unique=False, schema='erp')
    op.create_index(op.f('ix_erp_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False, schema='erp')
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='erp'
    )
    op.create_table('inspections',
    sa.Column('inspection_id', sa.String(length=16), nullable=False),
    sa.Column('serial_number', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('inspected_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('inspection_id'),
    schema='mes'
    )
    op.create_index(op.f('ix_mes_inspections_serial_number'), 'inspections', ['serial_number'], unique=False, schema='mes')
    op.create_table('nonconformances',
    sa.Column('ncr_id', sa.String(length=16), nullable=False),
    sa.Column('serial_number', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('ncr_id'),
    schema='mes'
    )
    op.create_index(op.f('ix_mes_nonconformances_serial_number'), 'nonconformances', ['serial_number'], unique=False, schema='mes')
    op.create_table('serials',
    sa.Column('serial_number', sa.String(length=16), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('serial_number'),
    schema='mes'
    )
    op.create_index(op.f('ix_mes_serials_part_number'), 'serials', ['part_number'], unique=False, schema='mes')
    op.create_table('work_orders',
    sa.Column('wo_id', sa.String(length=16), nullable=False),
    sa.Column('serial_number', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('blocked_reason', sa.String(length=160), nullable=True),
    sa.Column('depends_on_po', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('wo_id'),
    schema='mes'
    )
    op.create_index(op.f('ix_mes_work_orders_depends_on_po'), 'work_orders', ['depends_on_po'], unique=False, schema='mes')
    op.create_index(op.f('ix_mes_work_orders_serial_number'), 'work_orders', ['serial_number'], unique=False, schema='mes')
    op.create_table('bom_lines',
    sa.Column('bom_line_id', sa.String(length=16), nullable=False),
    sa.Column('parent_pn', sa.String(length=16), nullable=False),
    sa.Column('child_pn', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bom_line_id'),
    schema='plm'
    )
    op.create_index(op.f('ix_plm_bom_lines_child_pn'), 'bom_lines', ['child_pn'], unique=False, schema='plm')
    op.create_index(op.f('ix_plm_bom_lines_parent_pn'), 'bom_lines', ['parent_pn'], unique=False, schema='plm')
    op.create_table('parts',
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('revision', sa.String(length=4), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('unit_cost_usd', sa.Float(), nullable=False),
    sa.Column('export_controlled', sa.Boolean(), nullable=False),
    sa.Column('controlled_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('part_number'),
    schema='plm'
    )
    op.create_table('part_links',
    sa.Column('req_id', sa.String(length=16), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('req_id', 'part_number'),
    schema='req'
    )
    op.create_table('requirements',
    sa.Column('req_id', sa.String(length=16), nullable=False),
    sa.Column('text', sa.String(length=240), nullable=False),
    sa.Column('verification_method', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('req_id'),
    schema='req'
    )
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=60), nullable=False),
    sa.Column('workflow', sa.String(length=40), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('diff_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['app.eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False, schema='app')
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=4), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('disposition', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('guardrail_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=40), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_guardrail_results_run_id'), 'guardrail_results', ['run_id'], unique=False, schema='app')
    op.create_table('run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_run_steps_run_id'), 'run_steps', ['run_id'], unique=False, schema='app')
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=10), nullable=False),
    sa.Column('to_status', sa.String(length=10), nullable=False),
    sa.Column('disposition', sa.String(length=30), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['app.feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_feedback_events_feedback_id'), 'feedback_events', ['feedback_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_feedback_events_feedback_id'), table_name='feedback_events', schema='app')
    op.drop_table('feedback_events', schema='app')
    op.drop_index(op.f('ix_app_run_steps_run_id'), table_name='run_steps', schema='app')
    op.drop_table('run_steps', schema='app')
    op.drop_index(op.f('ix_app_guardrail_results_run_id'), table_name='guardrail_results', schema='app')
    op.drop_table('guardrail_results', schema='app')
    op.drop_table('feedback', schema='app')
    op.drop_index(op.f('ix_app_eval_results_eval_run_id'), table_name='eval_results', schema='app')
    op.drop_table('eval_results', schema='app')
    op.drop_table('requirements', schema='req')
    op.drop_table('part_links', schema='req')
    op.drop_table('parts', schema='plm')
    op.drop_index(op.f('ix_plm_bom_lines_parent_pn'), table_name='bom_lines', schema='plm')
    op.drop_index(op.f('ix_plm_bom_lines_child_pn'), table_name='bom_lines', schema='plm')
    op.drop_table('bom_lines', schema='plm')
    op.drop_index(op.f('ix_mes_work_orders_serial_number'), table_name='work_orders', schema='mes')
    op.drop_index(op.f('ix_mes_work_orders_depends_on_po'), table_name='work_orders', schema='mes')
    op.drop_table('work_orders', schema='mes')
    op.drop_index(op.f('ix_mes_serials_part_number'), table_name='serials', schema='mes')
    op.drop_table('serials', schema='mes')
    op.drop_index(op.f('ix_mes_nonconformances_serial_number'), table_name='nonconformances', schema='mes')
    op.drop_table('nonconformances', schema='mes')
    op.drop_index(op.f('ix_mes_inspections_serial_number'), table_name='inspections', schema='mes')
    op.drop_table('inspections', schema='mes')
    op.drop_table('suppliers', schema='erp')
    op.drop_index(op.f('ix_erp_purchase_orders_supplier_id'), table_name='purchase_orders', schema='erp')
    op.drop_index(op.f('ix_erp_purchase_orders_part_number'), table_name='purchase_orders', schema='erp')
    op.drop_table('purchase_orders', schema='erp')
    op.drop_table('wo_cycle_time', schema='dw')
    op.drop_table('supplier_on_time', schema='dw')
    op.drop_index(op.f('ix_app_runs_decision'), table_name='runs', schema='app')
    op.drop_table('runs', schema='app')
    op.drop_table('eval_runs', schema='app')
    op.drop_table('drift_scenarios', schema='app')
    op.drop_index(op.f('ix_app_drift_incidents_status'), table_name='drift_incidents', schema='app')
    op.drop_table('drift_incidents', schema='app')
    op.drop_table('contract_baselines', schema='app')
    # ### end Alembic commands ###
